clean:
	./gradlew clean

build:
	./gradlew clean build

run:
	./gradlew run

run-dist:
	./build/install/app/bin/app

run-help:
	./build/install/app/bin/app -h

run-file:
	./build/install/app/bin/app ./json1.json ./json2.json

.PHONY: build